version: '3.8'
services:
  db:
    image: postgres:14.2-alpine
    container_name: db
    expose:
      - 5432
    environment:
      - POSTGRES_USER=surmach
      - POSTGRES_PASSWORD=1111
      - POSTGRES_DB=employeedb
  activemq:
    image: rmohr/activemq:5.14.0-alpine
    container_name: activemq
    expose:
      - 61616
  simplewebapp:
    image: simplewebapp:latest
    build: .
    container_name: simplewebapp
    ports:
      - 8088:8088
    depends_on:
      - db
      - activemq
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/employeedb
      - APP_ACTIVEMQ_BROKER-URL=tcp://activemq:61616

